apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/frontend
  - ../../bases/backend
  - ../../cluster/namespaces/namespace-prod.yaml

patchesStrategicMerge:
  - frontend-patch.yaml
  - backend-patch.yaml

images:
  - name: nginx
    newTag: stable-alpine
  - name: alpine
    newTag: 3.18
