apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/frontend
  - ../../bases/backend
  - ../../cluster/namespaces/namespace-dev.yaml

# Example patches
patchesStrategicMerge:
  - frontend-patch.yaml
  - backend-patch.yaml

# Image tag overrides
images:
  - name: nginx
    newTag: alpine
  - name: alpine
    newTag: latest
