name: Deploy Helm

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      service:
        required: true
        type: string
      runs-on:
        required: false
        type: string
      environment:
        required: true
        type: string
      repository:
        required: true
        type: string
      values:
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true

run-name: Deploy to ${{ inputs.environment }} service: ${{ inputs.service }}

jobs:
  deploy:
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.PAT_TOKEN }}
          path: infra-repo
          ref: main

      - name: Update image tag
        env:
          IMAGE: ${{ inputs.image }}
        run: |
          cd infra-repo
          yq eval '.image = "$IMAGE"' -i ${{ inputs.values }}
          echo "Updated ${{ inputs.service }} environment: ${{ inputs.environment }} to image: $IMAGE"
          echo "values file:"
          cat ${{ inputs.values }}

      - name: Commit update
        run: |
          cd infra-repo
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ${{ inputs.values }}
          git commit -m "Deploy to ${{ inputs.environment }}: ${GITHUB_SHA::7}" || echo "No changes to commit"
          git push origin main

      - name: Finishing Deploy
        run: |
          echo "======= CONGRATULATIONS =========="
          echo "======= Deployment Finished ======"
